#!/usr/bin/env fish

#
# Desktops
#

bspc monitor --reset-desktops tty browse art chat media game file vm conf misc

#
# General
#

bspc config border_width 2
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config split_ratio 0.5
bspc config window_gap 8

#
# Colors
#

bspc config active_border_color '#5a5a5a'
bspc config focused_border_color '#5a5a5a'
bspc config normal_border_color '#252525'
bspc config presel_feedback_color '#080808'

#
# Rules
#

bspc rule --remove '*:*'
bspc rule --add Firefox desktop='^2'
bspc rule --add qutebrowser desktop='^2'
bspc rule --add Vivaldi-stable desktop='^2'
bspc rule --add Aseprite desktop='^3'
bspc rule --add Darktable desktop='^3' follow=on
bspc rule --add Gimp desktop='^3' follow=on
bspc rule --add krita desktop='^3'
bspc rule --add TelegramDesktop desktop='^4'
bspc rule --add Dwarf_Fortress desktop='^6'
bspc rule --add dwarftherapist desktop='^6'
bspc rule --add '*:floating' state=floating
bspc rule --add vlc state=floating
bspc rule --add Zathura desktop='^5' state=tiled
