ignore = ['fnl$', 'Makefile$', 'README.md$', 'soupmacs$', '\.unsafe$']
rage = 1

[dots]
alacritty = '~/.config/alacritty'
alsa = '~'
bash = '~'
bin = '~/.local/bin'
bspwm = '~/.config/bspwm'
dunst = '~/.config/dunst'
fish = '~/.config/fish'
lf = '~/.config/lf'
mopidy = '~/.config/mopidy'
mpd = '~/.config/mpd'
ncmpcpp = '~/.config/ncmpcpp'
polybar = '~/.config/polybar'
qutebrowser = '~/.config/qutebrowser'
rofi = '~/.config/rofi'
starship = '~/.config'
sx = '~/.config/sx'
sxhkd = '~/.config/sxhkd'
tmux = '~'
uma-dlc = '~/.config/nvim'
zathura = '~/.config/zathura'
