#!/usr/bin/env python3

from argparse import ArgumentParser
from os import environ, kill, path
from signal import SIGKILL
from subprocess import Popen, run
from sys import stderr


def get_parser():
  """Return the command line argument parser."""
  parser = ArgumentParser(description='launch a polybar bar')
  parser.add_argument('bar', help='name of the bar', metavar='name')
  return parser


def launch(args):
  """Launch the Polybar bar."""

  file = path.expanduser(f'~/.config/polybar/{args.bar}.ini')

  if not path.isfile(file):
    print("launch: bar file doesn't exist", file=stderr)
    exit(1)

  tmp = f'/tmp/polybar-{environ["USER"]}-{args.bar}'

  if path.exists(tmp):
    try:
      mqueue = path.basename(path.realpath(tmp))
      pid = int(mqueue.split('.')[1])
      kill(pid, SIGKILL)
    except:
      pass

  pid = Popen(['polybar', '-c', file, args.bar]).pid
  run(['ln', '--force', '--symbolic', f'/tmp/polybar_mqueue.{pid}', tmp])


if __name__ == '__main__':
  parser = get_parser()
  args = parser.parse_args()
  launch(args)
