#!/bin/bash

HELP='sxrc
Start a X session.

Usage
  sxrc
  sxrc -c <cmd> ...
  sxrc [-h] ...
  sxrc [--] <sesh> ...

Flags
      --      Treat next arguments as positional arguments.
  -h  --help  Print help information and exit.

Options
  -c  --cmd  <cmd>  Set custom command <cmd> to be executed.

Positional Arguments
  <sesh>  Set session <sesh> to be started. <sesh> may be "bspwm".'

bspwm() {
  export _JAVA_AWT_WM_NONREPARENTING=1
  export SHOT_DIR="$HOME/pix/shot"
  ~/.fehbg &
  SXHKD_SHELL=/bin/bash sxhkd ~/.config/sxhkd/bspwm.sxhkdrc &
  launch-bar bspwm &
  exec bspwm
}

die() { (($#)) && err "$@"; exit 1; }
err() { echo "[sxrc] [ERROR] $@" >&2; }

parse() {
  case $1 in
    '') SESH=bspwm ;;
    -c|--cmd) [[ $2 ]] || die "<cmd> not given"; CMD="$2" ;;
    -h|--help) echo "$HELP"; exit ;;
    --) [[ $2 ]] || die "<sesh> not given"; SESH="$2" ;;
    -*) die "Invalid argument: $1" ;;
    *) SESH="$1" ;;
  esac
}

run() {
  parse "$@"
  [[ $CMD ]] && exec $CMD
  case $SESH in
    bspwm) bspwm ;;
    *) die "Invalid value for <sesh>: $SESH" ;;
  esac
}

run "$@"
