#!/bin/bash

HELP='sxrc
start X session

USAGE
  sxrc
  sxrc -c <cmd> ...
  sxrc [-h] ...
  sxrc [--] <sesh> ...

FLAGS
      --      treat next arguments as positional arguments
  -h  --help  print help information and exit

OPTIONS
  -c  --cmd  <cmd>  set custom command <cmd> to be executed

POSITIONAL ARGUMENTS
  <sesh>  set session <sesh> to be started; <sesh> may be "bspwm"'

bspwm() {
  export _JAVA_AWT_WM_NONREPARENTING=1
  export SHOT_DIR="$HOME/pix/shot"
  ~/.fehbg &
  SXHKD_SHELL=/bin/bash sxhkd ~/.config/sxhkd/bspwm.sxhkdrc &
  launch-bar bspwm &
  exec bspwm
}

die() { (($#)) && err "$@"; exit 1; }
err() { echo "sxrc: ERROR: $@" >&2; }

parse() {
  case $1 in
    '') SESH=bspwm ;;
    -c|--cmd) [[ $2 ]] || die "<cmd> not given"; CMD="$2" ;;
    -h|--help) echo "$HELP"; exit ;;
    --) [[ $2 ]] || die "<sesh> not given"; SESH="$2" ;;
    -*) die "invalid argument: $1" ;;
    *) SESH="$1" ;;
  esac
}

run() {
  parse "$@"
  [[ $CMD ]] && exec $CMD
  case $SESH in
    bspwm) bspwm ;;
    *) die "invalid value for <sesh>: $SESH" ;;
  esac
}

run "$@"
