add_newline = false

[character]
error_symbol = '[\$](bold fg:1)'
success_symbol = '[\$](bold fg:2)'
vicmd_symbol = '[\$](bold fg:6)'

[directory]
style = 'bold fg:2'

[line_break]
disabled = true

[package]
disabled = true
