add_newline = false

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[character]
error_symbol = '[❱](bold fg:1)'
success_symbol = '[❱](bold fg:2)'
vicmd_symbol = '[](bold fg:14)'

[cmake]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = '[ $duration]($style) '

[conda]
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol($version )]($style)'

[dart]
format = '[$symbol($version )]($style)'

[deno]
format = '[$symbol($version )]($style)'

[docker_context]
format = '[$symbol$context]($style) '

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
format = '[$symbol($version )]($style)'

[erlang]
format = '[$symbol($version )]($style)'

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
format = '[$symbol$branch]($style)(:[$remote]($style)) '

[git_status]
style = 'bold fg:13'

[golang]
format = '[$symbol($version )]($style)'

[helm]
format = '[$symbol($version )]($style)'

[hg_branch]
format = '[$symbol$branch]($style) '

[hostname]
format = '[$hostname]($style) '

[java]
format = '[$symbol($version )]($style)'

[julia]
format = '[$symbol($version )]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[line_break]
disabled = true

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[memory_usage]
format = '$symbol[$ram( | $swap)]($style) '

[nim]
format = '[$symbol($version )]($style)'

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
format = '[$symbol($version )]($style)'

[ocaml]
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[package]
disabled = true
format = '[$symbol$version]($style) '

[perl]
format = '[$symbol($version )]($style)'

[php]
format = '[$symbol($version )]($style)'

[purescript]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '

[rlang]
format = '[$symbol($version )]($style)'

[red]
format = '[$symbol($version )]($style)'

[ruby]
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'
symbol = ' '

[scala]
format = '[$symbol($version )]($style)'

[status]
disabled = false

[swift]
format = '[$symbol($version )]($style)'

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[ $time]($style) '

[username]
format = '[$user]($style) '

[vlang]
format = '[$symbol($version )]($style)'

[vagrant]
format = '[$symbol($version )]($style)'

[zig]
format = '[$symbol($version )]($style)'
