local function config()
  do end (require("harpoon")).setup({global_settings = {enter_on_sendcmd = true}})
  local term
  if vim.fn.exists("$TMUX") then
    term = "tmux"
  else
    term = "term"
  end
  local fmt = string.format
  return (require("which-key")).register({["[j"] = {"<Cmd>lua require'harpoon.ui'.nav_prev()<CR>", "Harpoon go to previous mark"}, ["]j"] = {"<Cmd>lua require'harpoon.ui'.nav_next()<CR>", "Harpoon go to next mark"}, j = {name = "Harpoon", ["0"] = {"<Cmd>lua require'harpoon.ui'.nav_file(10)<CR>", "Go to file #10"}, ["1"] = {"<Cmd>lua require'harpoon.ui'.nav_file(1)<CR>", "Go to file #1"}, ["2"] = {"<Cmd>lua require'harpoon.ui'.nav_file(2)<CR>", "Go to file #2"}, ["3"] = {"<Cmd>lua require'harpoon.ui'.nav_file(3)<CR>", "Go to file #3"}, ["4"] = {"<Cmd>lua require'harpoon.ui'.nav_file(4)<CR>", "Go to file #4"}, ["5"] = {"<Cmd>lua require'harpoon.ui'.nav_file(5)<CR>", "Go to file #5"}, ["6"] = {"<Cmd>lua require'harpoon.ui'.nav_file(6)<CR>", "Go to file #6"}, ["7"] = {"<Cmd>lua require'harpoon.ui'.nav_file(7)<CR>", "Go to file #7"}, ["8"] = {"<Cmd>lua require'harpoon.ui'.nav_file(8)<CR>", "Go to file #8"}, ["9"] = {"<Cmd>lua require'harpoon.ui'.nav_file(9)<CR>", "Go to file #9"}, a = {"<Cmd>lua require'harpoon.mark'.add_file()<CR>", "Harpoon push current file"}, j = {"<Cmd>lua require'harpoon.ui'.toggle_quick_menu()<CR>", "Harpoon toggle quick menu"}, t = {("<Cmd>lua require'harpoon." .. term .. "'.gotoTerminal(1)<CR>"), "Harpoon go to terminal"}, c = {name = "Commands", ["0"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 10), "Send command #10"}, ["1"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 1), "Send command #1"}, ["2"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 2), "Send command #2"}, ["3"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 3), "Send command #3"}, ["4"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 4), "Send command #4"}, ["5"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 5), "Send command #5"}, ["6"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 6), "Send command #6"}, ["7"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 7), "Send command #7"}, ["8"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 8), "Send command #8"}, ["9"] = {fmt("<Cmd>lua require'harpoon'.%s.sendCommand(1, %d)<CR>", term, 9), "Send command #9"}, c = {"<Cmd>lua require'harpoon.cmd-ui'.toggle_quick_menu()<CR>", "Harpoon toggle command quick menu"}}}}, {prefix = "<Leader>"})
end
return {config = config}
